web:
    image: nginx:latest
    container_name: docker_nginx
    ports:
        - "8080:80"
    volumes: 
        - /home/drake/app:/app
        - /home/drake/docker/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    container_name: docker_php7
    volumes: 
        - /home/drake/app:/app
    links: 
        - mysql
mysql:
    image: mysql
    container_name: docker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes: 
        - /home/drake/app:/app

