web:
    image: nginx:latest
    container_name: docker_nginx
    ports:
        - "8080:80"
    volumes: 
        - /home/drake/app:/app
        - /home/drake/docker/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    container_name: docker_php7
    volumes: 
        - /home/drake/app:/app
    links: 
        - redis
redis:
    container_name: docker_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always